// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	agentOverview: (agent: Agent) => typedError<Overview, string>(__TAURI_INVOKE("agent_overview", { agent })),
	adopt: (agent: Agent) => typedError<null, string>(__TAURI_INVOKE("adopt", { agent })),
	importUnmanaged: (agent: Agent) => typedError<null, string>(__TAURI_INVOKE("import_unmanaged", { agent })),
	saveProfile: (agent: Agent, profile: Profile) => typedError<null, string>(__TAURI_INVOKE("save_profile", { agent, profile })),
	deleteProfile: (agent: Agent, name: string) => typedError<null, string>(__TAURI_INVOKE("delete_profile", { agent, name })),
	activateProfile: (agent: Agent, name: string) => typedError<null, string>(__TAURI_INVOKE("activate_profile", { agent, name })),
	unlinkKind: (agent: Agent, kind: Kind) => typedError<null, string>(__TAURI_INVOKE("unlink_kind", { agent, kind })),
	getHookMeta: (agent: Agent, name: string) => typedError<HookMeta, string>(__TAURI_INVOKE("get_hook_meta", { agent, name })),
	saveHookMeta: (agent: Agent, name: string, meta: HookMeta) => typedError<null, string>(__TAURI_INVOKE("save_hook_meta", { agent, name, meta })),
};

/** Events */
export const events = {
	overviewChanged: makeEvent<OverviewChanged>("overview-changed"),
};

/* Types */
export type Agent = "claude" | "codex";

/**  Hook 1 件に付随するメタデータ。フィールドはすべて省略可能で、未設定の場合は None。 */
export type HookMeta = {
	/**  トリガーするイベント種別 (例: "PreToolUse", "PostToolUse", "PreCompact") */
	event: string | null,
	/**  実行ランタイム (例: "bash", "python3") */
	runtime: string | null,
	/**  タイムアウト秒数 */
	timeout: number | null,
	/**  同一イベント内での実行順 */
	order: number | null,
	/**  人が読む説明文 */
	description: string | null,
};

/**  種類ごとの項目名の一覧。ライブラリの内容にも、 Profile の有効項目にも使う。 */
export type Items = {
	skills: string[],
	agents: string[],
	hooks: string[],
	rules: string[],
};

export type Kind = "skills" | "agents" | "hooks" | "rules";

/**  Agent 側ディレクトリ 1 種類分の現況。 */
export type KindStatus = {
	kind: Kind,
	dirPath: string,
	/**  ディレクトリ自体がシンボリックリンクで、変更対象外になっている */
	dirIsSymlink: boolean,
	/**  このアプリが置いたリンク */
	linked: string[],
	/**  Agent が管理している項目(対象外) */
	system: string[],
	/**  ユーザーが置いたが、まだ取り込まれていない項目 */
	unmanaged: string[],
};

export type Overview = {
	adopted: boolean,
	active: string | null,
	profiles: Profile[],
	library: Items,
	links: KindStatus[],
};

/**  ミューテーション成功後に emit するイベント。フロントはこれを受けて overview を再取得する。 */
export type OverviewChanged = {
	agent: Agent,
};

/**  各 Skill / SubAgent / Hook / Rule の有効状態をまとめたもの。 */
export type Profile = {
	name: string,
	enabled: Items,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

